version: '3.4'
services:
    wag-docker:
        container_name: wag
        env_file:
          - .env
        build:
          context: .
          args:
            WEB_USER: ${WEB_USER}
            WEB_PWD: ${WEB_PWD}
        ports:
          - '4433:4433/tcp'
          - '7080:7080/tcp'
          - '8009:8009/udp'
          - '443:443/tcp'
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        ulimits:
# see PR #1
          memlock: -1
          nofile:
            soft: "65536"
            hard: "65536"
# tests with complete reg/auth didn't require privileged, so it is optional
#        privileged: true
        volumes:
          - './cfg:/cfg:z'
          - './data:/data:z'
